# Generated by Django 3.2.8 on 2022-03-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220304_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='select',
            field=models.CharField(max_length=256, null=True, verbose_name='User name'),
        ),
    ]
