# Generated by Django 3.2.8 on 2022-03-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_feedback_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='select',
            field=models.CharField(max_length=256, null=True, verbose_name='Room'),
        ),
    ]
