# Generated by Django 3.2.8 on 2022-03-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_feedback_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='number_children',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number children'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='number_person',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number person'),
        ),
    ]
